server:
  port: 9000

spring:
  application:
    name: member-provider
    # =====注册配置中心信息========
  cloud:
    nacos:
      discovery:
        server-addr: 118.31.63.122:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=CST
      username: root
      password: 123456
      initial-size: 10
      max-active: 50
      min-idle: 10
      filters: stat,slf4j,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.css,*.js"
      stat-view-servlet:
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
        reset-enable: false
mybatis:
    mapper-locations: classpath:/mapper/**/*.xml
    type-aliases-package:
    configuration:
      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
      map-underscore-to-camel-case: true
